# -*- coding: utf-8 -*-
"""Manipulacion datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XX1FMkh7foN0SdLhO9cSFi4lSRwRywwX
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas import ExcelWriter
# %matplotlib inline


df=pd.read_excel("base de datos (1).xlsx")

df.head()

df.sample(6)

df.tail()

df = df[["Nombre", "Apellido", "Departamento", "Sección", "Matrícula", "Salario", "Fecha ingreso"]]
df.head()

df.tail()

df.sample(6)

Copiadoras=df[df.Sección == "Copiadoras"]
Copiadoras

writer = ExcelWriter('copiadoras.xlsx')
df.to_excel(writer, 'Hoja de datos', index=False)
writer.save()
